### PR TITLE
Test closure in DB DataCollector

### PR DESCRIPTION
**Pull request by pachico**
As in https://github.com/phpab/phpab/issues/83, too much is happening inside DataCollectors without being tested nor having their inputs validated.
This is an attempt to fix that.

### CODE REVIEW

**Comment by HellPat** [comment]
I'm not sure about this.

Here the conversation from gitter. @waltertamboer maybe we need your input here.

> Patrick @psren 23:22
> I’m not sure about all the assertions in your branch.
> The Event-Subscribers are for the specific events of the implementation of Engine. And so they can safely rely on the parametes passed by the events.
> I’d rather vote for testing if the events are getting fired with the correct parameters in our Engine implementation
> 
> Mariano Benítez Mulet @pachico 23:22
> I see, I didn't take in consideration that Engine might change
> but somehow, that implies that a lot of functionality will become either coupled or untested
> 
> Patrick @psren 23:25
> Coupled to Engine, yes. But Engine will most likely not change, and if so it should comply to the tests. I’m not sure about that.
> We could use a callback instead of a closure and then call_user_func_array that thing in our EventSubscriber

**Comment by waltertamboer** [comment]
So I'm trying to understand the problem. We have this type of code where the callback is not covered in the unit tests, am I right?

``` php
<?php

class DataCollector implements SubscriberInterface
{
    public function getSubscribedEvents()
    {
        return [
            '...' => function ($options) {
                // This is not covered in the unit test.
            },
        ];
    }
}
```

We could simply change it to:

``` php
<?php

class DataCollector implements SubscriberInterface
{
    public function getSubscribedEvents()
    {
        return [
            '...' => [$this, 'onAction'],
        ];
    }

    public function onAction($options)
    {
        // This can now be covered.
        // It's common sense to never call an on* method.
    }
}
```

**Comment by HellPat** [comment]
Correct @waltertamboer

**Comment by waltertamboer** [comment]
So can we just make it a public method? That would solve the problem.

**Comment by pachico** [comment]
Seems like a good approach, indeed

**Comment by pachico** [comment]
I changed my mind.
Honestly we don't solve anything with this since the problem wasn't that we COULDN'T cover that functionality, simply that we DIDN'T.
The test implemented in this PR would be exactly the one you'd need for this approach.
The objections were about the assertions rather than the closure.

**Pull request merged**
